# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000000
HISTFILESIZE=2000000

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
shopt -s globstar

# Use Vi style commands on the shell (in insert mode by defualt)
set -o vi
# switch back to emacs : set -o emacs
# Clear screen with C-l also in insert mode
bind -m vi-insert "\C-l":clear-screen

# VIM
export VISUAL=vim
export EDITOR=vim

# GPG prompt: use tty
export GPG_TTY=$(tty)

# CORE
ulimit -c unlimited

# Go
export GOPATH="$HOME/go"
export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin

# Tabs size in terminal
tabs -4
export LESS=Rx4

# Python SSL
export REQUESTS_CA_BUNDLE="/etc/ssl/certs/ca-certificates.crt"
# Python warnings
export PYTHONWARNINGS="once:Unverified HTTPS request"
